$Host.UI.RawUI.WindowTitle = "TicketOps Asset Ping - 287 Devices"
Clear-Host
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "   TICKETOPS LIVE ASSET CONNECTIVITY CHECK     " -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "Started at: $(Get-Date)"
Write-Host ""
Write-Host "[...] Pinging SMC-CAM-01      (10.0.66.119    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.119 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-02      (10.0.66.120    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.120 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-03      (10.0.66.121    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.121 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-04      (10.0.66.26     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.26 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-05      (10.0.66.27     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.27 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-06      (10.0.66.28     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.28 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-07      (10.0.66.29     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.29 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-08      (10.0.66.160    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.160 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-09      (10.0.66.161    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.161 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-10      (10.0.66.162    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.162 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-11      (10.0.66.163    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.163 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-12      (10.0.66.36     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.36 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-13      (10.0.66.37     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.37 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-14      (10.0.66.38     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.38 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-15      (10.0.66.46     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.46 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-16      (10.0.66.47     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.47 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-17      (10.0.66.48     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.48 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-18      (10.0.66.49     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.49 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-19      (10.0.66.184    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.184 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-20      (10.0.66.185    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.185 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-21      (10.0.66.186    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.186 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-22      (10.0.66.187    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.187 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-23      (10.0.66.17     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.17 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-24      (10.0.66.18     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.18 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-25      (10.0.66.171    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.171 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-26      (10.0.66.172    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.172 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-27      (10.0.66.173    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.173 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-28      (10.0.66.110    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.110 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-29      (10.0.66.111    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.111 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-30      (10.0.66.112    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.112 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-31      (10.0.66.148    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.148 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-32      (10.0.66.149    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.149 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-33      (10.0.66.174    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.174 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-34      (10.0.66.175    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.175 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-35      (10.0.66.122    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.122 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-36      (10.0.66.50     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.50 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-37      (10.0.66.51     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.51 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-38      (10.0.66.53     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.53 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-39      (10.0.66.54     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.54 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-40      (10.0.66.52     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.52 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-41      (10.0.66.102    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.102 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-42      (10.0.66.103    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.103 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-43      (10.0.66.104    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.104 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-44      (10.0.66.65     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.65 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-45      (10.0.66.66     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.66 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-46      (10.0.66.67     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.67 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-01      (10.0.66.210    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.210 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-02      (10.0.66.176    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.176 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-03      (10.0.66.224    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.224 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-04      (10.0.66.221    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.221 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-05      (10.0.66.225    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.225 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-06      (10.0.66.222    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.222 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-07      (10.0.67.16     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.67.16 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-FRS-08      (10.0.66.223    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.223 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-47      (10.0.66.108    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.108 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-48      (10.0.66.109    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.109 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-49      (10.0.66.30     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.30 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-50      (10.0.66.31     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.31 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-51      (10.0.66.32     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.32 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-52      (10.0.66.135    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.135 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-53      (10.0.66.136    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.136 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-54      (10.0.66.137    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.137 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-55      (10.0.66.100    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.100 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-56      (10.0.66.101    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.101 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-57      (10.0.66.79     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.79 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-58      (10.0.66.80     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.80 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-59      (10.0.66.81     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.81 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-60      (10.0.66.113    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.113 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-61      (10.0.66.114    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.114 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-62      (10.0.66.167    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.167 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-63      (10.0.66.168    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.168 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-64      (10.0.66.169    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.169 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-65      (10.0.66.170    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.170 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-66      (10.0.66.150    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.150 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-67      (10.0.66.151    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.151 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-68      (10.0.66.152    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.152 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-69      (10.0.66.78     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.78 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-70      (10.0.66.74     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.74 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-71      (10.0.66.75     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.75 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-72      (10.0.66.76     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.76 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-73      (10.0.66.77     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.77 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-74      (10.0.66.42     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.42 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-75      (10.0.66.43     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.43 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-76      (10.0.66.44     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.44 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-77      (10.0.66.45     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.45 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-78      (10.0.66.33     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.33 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-79      (10.0.66.34     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.34 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-80      (10.0.66.35     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.35 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-81      (10.0.66.59     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.59 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-82      (10.0.66.60     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.60 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-83      (10.0.66.61     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.61 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-84      (10.0.66.39     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.39 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-85      (10.0.66.40     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.40 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-86      (10.0.66.41     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.41 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-87      (10.0.66.156    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.156 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-88      (10.0.66.157    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.157 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-89      (10.0.66.158    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.158 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-90      (10.0.66.159    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.159 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-91      (10.0.66.10     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.10 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-92      (10.0.66.11     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.11 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-93      (10.0.66.12     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.12 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-94      (10.0.66.13     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.13 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-95      (10.0.66.14     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.14 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-96      (10.0.66.177    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.177 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-97      (10.0.66.178    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.178 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-98      (10.0.66.179    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.179 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-99      (10.0.66.68     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.68 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-100     (10.0.66.69     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.69 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-101     (10.0.66.70     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.70 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-102     (10.0.66.94     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.94 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-103     (10.0.66.95     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.95 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-104     (10.0.66.96     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.96 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-105     (10.0.66.22     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.22 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-106     (10.0.66.23     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.23 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-107     (10.0.66.24     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.24 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-108     (10.0.66.25     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.25 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-01      (10.0.66.217    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.217 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-02      (10.0.66.212    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.212 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-03      (10.0.66.216    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.216 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-04      (10.0.66.207    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.207 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-05      (10.0.66.206    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.206 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-06      (10.0.65.43     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.43 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-07      (10.0.66.202    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.202 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PTZ-08      (10.0.66.208    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.208 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-109     (10.0.66.62     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.62 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-110     (10.0.66.63     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.63 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-111     (10.0.66.64     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.64 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-112     (10.0.66.181    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.181 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-113     (10.0.66.182    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.182 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-114     (10.0.66.183    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.183 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-115     (10.0.66.15     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.15 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-116     (10.0.66.16     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.16 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-117     (10.0.66.105    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.105 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-118     (10.0.66.106    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.106 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-119     (10.0.66.107    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.107 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-120     (10.0.66.55     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.55 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-121     (10.0.66.56     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.56 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-122     (10.0.66.57     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.57 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-123     (10.0.66.58     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.58 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-124     (10.0.66.138    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.138 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-125     (10.0.66.139    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.139 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-126     (10.0.66.140    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.140 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-127     (10.0.66.141    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.141 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-128     (10.0.66.19     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.19 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-129     (10.0.66.20     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.20 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-130     (10.0.66.21     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.21 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-131     (10.0.66.115    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.115 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-132     (10.0.66.116    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.116 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-133     (10.0.66.117    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.117 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-134     (10.0.66.118    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.118 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-135     (10.0.66.84     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.84 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-136     (10.0.66.85     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.85 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-137     (10.0.66.86     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.86 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-138     (10.0.66.153    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.153 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-139     (10.0.66.154    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.154 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-140     (10.0.66.155    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.155 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-141     (10.0.66.131    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.131 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-142     (10.0.66.132    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.132 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-143     (10.0.66.133    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.133 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-CAM-144     (10.0.66.134    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.134 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-01     (10.0.66.230    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.230 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-03     (10.0.66.232    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.232 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-04     (10.0.66.233    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.233 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-05     (10.0.66.234    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.234 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-06     (10.0.66.235    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.235 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-07     (10.0.66.236    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.236 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-08     (10.0.66.237    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.237 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-09     (10.0.66.238    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.238 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-10     (10.0.66.239    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.239 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-11     (10.0.66.240    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.240 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-ALPR-12     (10.0.66.241    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.241 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-01       (10.0.66.190    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.190 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-02       (10.0.66.191    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.191 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-03       (10.0.66.192    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.192 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-04       (10.0.66.193    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.193 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-05       (10.0.66.194    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.194 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-06       (10.0.66.195    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.195 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-07       (10.0.66.196    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.196 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-08       (10.0.66.197    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.197 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-09       (10.0.66.198    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.198 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-10       (10.0.66.199    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.199 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-11       (10.0.66.200    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.200 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-PA-12       (10.0.66.201    )... " -NoNewline; if (Test-Connection -ComputerName 10.0.66.201 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[-] SMC-UPS-01      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-02      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-03      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-04      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-05      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-06      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-07      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-08      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-09      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-10      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-11      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-12      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-13      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-14      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-15      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-16      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-17      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-18      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-19      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-20      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-21      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-22      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-23      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-24      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-25      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-26      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-27      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-28      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-29      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-30      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-31      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-32      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-33      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-34      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-35      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-36      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-37      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-38      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-39      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-40      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-41      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-42      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-UPS-43      | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-Firewall    | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-Management-Server | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-Archiver-Server-01 | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-Archiver-Server-02 | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-Plugin-Server | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-Incidentmanagment Server | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-NAS         | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-PC-01       | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-PC-02       | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-PC-03       | Passive Device" -ForegroundColor Gray
Write-Host "[-] SMC-PC-04       | Passive Device" -ForegroundColor Gray
Write-Host "[...] Pinging SMC-SWITCH-01   (10.0.65.1      )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.1 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-02   (10.0.64.1      )... " -NoNewline; if (Test-Connection -ComputerName 10.0.64.1 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-03   (10.0.65.10     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.10 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-04   (10.0.65.11     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.11 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-05   (10.0.65.12     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.12 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-06   (10.0.65.13     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.13 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-07   (10.0.65.14     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.14 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-08   (10.0.65.15     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.15 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-09   (10.0.65.16     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.16 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-10   (10.0.65.17     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.17 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-11   (10.0.65.18     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.18 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-12   (10.0.65.19     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.19 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-13   (10.0.65.20     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.20 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-14   (10.0.65.21     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.21 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-15   (10.0.65.22     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.22 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-16   (10.0.65.23     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.23 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-17   (10.0.65.24     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.24 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-18   (10.0.65.25     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.25 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-19   (10.0.65.26     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.26 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-20   (10.0.65.27     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.27 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-21   (10.0.65.28     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.28 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-22   (10.0.65.29     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.29 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-23   (10.0.65.30     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.30 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-24   (10.0.65.31     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.31 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-25   (10.0.65.34     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.34 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-26   (10.0.65.35     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.35 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-27   (10.0.65.36     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.36 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-28   (10.0.65.37     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.37 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-29   (10.0.65.38     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.38 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-30   (10.0.65.39     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.39 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-31   (10.0.65.40     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.40 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-32   (10.0.65.41     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.41 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-33   (10.0.65.42     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.42 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-34   (10.0.65.43     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.43 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-35   (10.0.65.46     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.46 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-36   (10.0.65.47     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.47 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-37   (10.0.65.48     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.48 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-38   (10.0.65.51     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.51 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-39   (10.0.65.52     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.52 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-40   (10.0.65.53     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.53 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-41   (10.0.65.54     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.54 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-42   (10.0.65.55     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.55 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-43   (10.0.65.56     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.56 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-44   (10.0.65.57     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.57 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-45   (10.0.65.58     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.58 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-46   (10.0.65.59     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.59 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-47   (10.0.65.60     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.60 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-48   (10.0.65.61     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.61 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-49   (10.0.65.63     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.63 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host "[...] Pinging SMC-SWITCH-50   (10.0.65.64     )... " -NoNewline; if (Test-Connection -ComputerName 10.0.65.64 -Count 1 -Quiet) { Write-Host "ONLINE" -ForegroundColor Green } else { Write-Host "OFFLINE" -ForegroundColor Red }
Write-Host ""
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "Check Complete. Results synced to Dashboard.   " -ForegroundColor Yellow
Write-Host "Press any key to close this window..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")