export const PERMISSIONS = {
    CREATE_TICKET: 'CREATE_TICKET',
    EDIT_TICKET: 'EDIT_TICKET',
    DELETE_TICKET: 'DELETE_TICKET',
    VIEW_REPORTS: 'VIEW_REPORTS',
    MANAGE_USERS: 'MANAGE_USERS',
    MANAGE_SITES: 'MANAGE_SITES',
    MANAGE_ASSETS: 'MANAGE_ASSETS'
};

export const PERMISSION_LABELS = {
    [PERMISSIONS.CREATE_TICKET]: 'Create Tickets',
    [PERMISSIONS.EDIT_TICKET]: 'Edit Tickets',
    [PERMISSIONS.DELETE_TICKET]: 'Delete Tickets',
    [PERMISSIONS.VIEW_REPORTS]: 'View Reports',
    [PERMISSIONS.MANAGE_USERS]: 'Manage Users',
    [PERMISSIONS.MANAGE_SITES]: 'Manage Sites',
    [PERMISSIONS.MANAGE_ASSETS]: 'Manage Assets'
};
